version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    rebase-strategy: "disabled"
    schedule:
      interval: weekly
      day: "saturday"
      timezone: "Europe/Berlin"
      time: "03:00"

  - package-ecosystem: npm
    directory: /
    rebase-strategy: "disabled"
    schedule:
      interval: weekly
      day: "saturday"
      timezone: "Europe/Berlin"
      time: "03:00"
