name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
    - title: '🚀 New'
      labels:
          - '🚀 Feature'
    - title: '🧹 Updates'
      labels:
          - '🧹 Updates'
          - '🤖 Dependencies'
          - 'dependencies'
    - title: '🐛 Fixes'
      labels:
          - '☢️ Bug'
    - title: '📚 Documentation'
      labels:
          - '📒 Documentation'
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
    major:
        labels:
            - 'major'
    minor:
        labels:
            - 'minor'
            - '🚀 Feature'
    patch:
        labels:
            - 'patch'
            - '📒 Documentation'
            - '☢️ Bug'
            - '🤖 Dependencies'
            - 'dependencies'
            - '🧹 Updates'
    default: patch
autolabeler:
    - label: '📒 Documentation'
      files:
          - '*.md'
      branch:
          - '/docs/i'
          - '/doc:/i'
          - '/\[doc\]/i'
          - '/README/i'
          - '/typos/i'
          - '/comment/i'
          - '/📚/i'
          - '/📒/i'
          - '/📝/i'
          - '/documentation/i'
    - label: '☢️ Bug'
      branch:
          - '/fix/i'
          - '/race/i'
          - '/bug/i'
          - '/missing/i'
          - '/correct/i'
          - '/🐛/i'
          - '/☢/i'
          - '/🩹/i'
          - '/🚨/i'
    - label: '🧹 Updates'
      branch:
          - '/improve/i'
          - '/update/i'
          - '/refactor/i'
          - '/deprecated/i'
          - '/remove/i'
          - '/unused/i'
          - '/test/i'
          - '/⚡/i'
          - '/👷/i'
          - '/🚧/i'
          - '/♻️/i'
          - '/🎨/i'
          - '/🧪/i'
          - '/🧹/i'
    - label: '🤖 Dependencies'
      branch:
          - '/bumb/i'
          - '/dependencies/i'
          - '/📦/i'
          - '/🤖/i'
    - label: '🚀 Feature'
      branch:
          - '/feature/i'
          - '/create/i'
          - '/implement/i'
          - '/add/i'
          - '/🚀/i'
          - '/✨/i'
          - '/🔥/i'
exclude-contributors:
    - '8BitJonny'
template: |
    $CHANGES

    **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

    Thank you $CONTRIBUTORS for making this update possible.
