name: Get Current Pull Request
author: 8BitJonny
description: Get the PR associated with the current commit.
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client.
    required: true
  sha:
    description: Sha to get PR for.  Defaults to current sha.
    required: false
  filterOutClosed:
    description: True, False, 1 or 0 if only open PRs should be returned
    required: false
outputs:
  pr:
    description: The whole PR object if one was found.
  number:
    description: The PR number if one was found.
  pr_title:
    description: The PR Title if one was found.
  pr_body:
    description: The PR Body if one was found.
  pr_url:
    description: The PR Url if one was found.
  pr_created_at:
    description: The PR Created timestamp if one was found.
  pr_merged_at:
    description: The PR Merged timestamp if one was found.
  pr_closed_at:
    description: The PR Closed timestamp if one was found.
runs:
  using: node12
  main: 'index.js'
branding:
  icon: git-pull-request
  color: green
