name: 'build'

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # 3.9.1
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: |
          npm run build
  clean-run: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # 3.9.1
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - name: Lint
        run: |
          npm run format-check
          npm run lint
