on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Returns the PR number
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Find PR
        uses: ./
        id: findPR
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get the pr number
        run: echo "The PR was ${{ steps.findPR.outputs.pr }}"
