on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Returns the PR number
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get PR
        uses: ./
        id: getPR
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Display PR properties
        run: |
          echo "The PR Number is ${{ steps.getPR.outputs.number }}"
          echo "The PR Title is ${{ steps.getPR.outputs.pr_title }}"
          echo "The PR Body is ${{ steps.getPR.outputs.pr_body }}"
          echo "The PR Url is ${{ steps.getPR.outputs.pr_url }}"
          echo "The PR Created_At is ${{ steps.getPR.outputs.pr_created_at }}"
          echo "The PR Merged_At is ${{ steps.getPR.outputs.pr_merged_at }}"
          echo "The PR Closed_At is ${{ steps.getPR.outputs.pr_closed_at }}"
          echo "The PR Labels are ${{ steps.getPR.outputs.pr_labels }}"
