on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Returns the PR number
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get PR
        uses: ./
        id: getPR
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get the pr number
        run: echo "The PR was ${{ steps.getPR.outputs.number }}"
