name: 'test'

on:
  push:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2  # v4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020  # v4.4.0
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: |
          npm test
  test-if-closed-pr-is-found:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2  # v4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020  # v4.4.0
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - name: Build Action
        run: |
          npm run build
          npm run package
      - name: Run Action
        uses: ./
        id: pr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sha: "44b060a85b83f5baf49f523d8a58444ccca52ead"
      - name: Assert PR properties
        run: |
          [[ ${{ steps.pr.outputs.pr_found }} == true ]] || (echo "outputs.pr_found != true"; exit 1)
          [[ ${{ steps.pr.outputs.number }} == 5 ]] || (echo "outputs.number != 5"; exit 1)
  test-if-closed-pr-is-not-found-when-filtering-closed-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2  # v4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020  # v4.4.0
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - name: Build Action
        run: |
          npm run build
          npm run package
      - name: Run Action
        uses: ./
        id: pr
        with:
          filterOutClosed: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sha: "44b060a85b83f5baf49f523d8a58444ccca52ead"
      - name: Exit 1, if PR was falsely found
        if: steps.pr.outputs.pr_found != 'false'
        run: echo "if 'outputs.pr_found' falsely triggered"; exit 1
      - name: Assert PR properties
        run: |
          [[ '${{ steps.pr.outputs.number }}' == '' ]] || (echo "PR falsely found"; exit 1)
