name: 'test'

on:
  push:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # 3.9.1
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: |
          npm test
  test-if-closed-pr-is-found:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # 3.9.1
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - name: Build Action
        run: |
          npm run build
          npm run package
      - name: Run Action
        uses: ./
        id: pr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sha: "44b060a85b83f5baf49f523d8a58444ccca52ead"
      - name: Assert PR properties
        run: |
          [[ ${{ steps.pr.outputs.pr_found }} == true ]] || (echo "outputs.pr_found != true"; exit 1)
          [[ ${{ steps.pr.outputs.number }} == 5 ]] || (echo "outputs.number != 5"; exit 1)
  test-if-closed-pr-is-not-found-when-filtering-closed-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # 3.9.1
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - name: Build Action
        run: |
          npm run build
          npm run package
      - name: Run Action
        uses: ./
        id: pr
        with:
          filterOutClosed: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sha: "44b060a85b83f5baf49f523d8a58444ccca52ead"
      - name: Exit 1, if PR was falsely found
        if: steps.pr.outputs.pr_found != 'false'
        run: echo "if 'outputs.pr_found' falsely triggered"; exit 1
      - name: Assert PR properties
        run: |
          [[ '${{ steps.pr.outputs.number }}' == '' ]] || (echo "PR falsely found"; exit 1)
